name: "Deploy in server"

on: 
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
#     - name: Basic settings
#       run: |
#           apt-get install curl -y
#           apt-get install git -y
#           apt-get install unzip -y
#           apt-get install zip -y
#           apt-get install xz-utils
    
    - name: Install dependencies
      run: npm install
      
    - name:  Build front-end
      run: npm  run build-prod
      
    - name: Deploy hosting on Linux server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        rm: true
        strip_components: 3
        source: "./build"
        target: "/var/docker/volumes/netflixclone"
        
